# Generated by Django 4.2.7 on 2023-12-04 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuue_type', models.CharField(max_length=150)),
                ('issues_description', models.TextField()),
                ('product_type', models.CharField(max_length=200)),
                ('unit_no', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('reported_by', models.CharField(max_length=300)),
                ('agent_id', models.CharField(max_length=50)),
                ('agent_phone', models.CharField(max_length=20)),
                ('agent_email', models.EmailField(max_length=254, unique=True)),
                ('resolved', models.BooleanField()),
                ('agent_response', models.TextField()),
                ('reported_at', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
