# Generated by Django 4.2.7 on 2023-12-04 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('issuesApp', '0002_alter_issue_agent_email_alter_issue_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
