# Generated by Django 4.2.7 on 2023-12-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuesApp', '0003_alter_issue_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=200)),
                ('agent_phone', models.CharField(max_length=20)),
                ('agent_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('reqion', models.CharField(max_length=100)),
                ('ahq', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
